### ISSUE TITLE
是不是应该把编译脚本中所有的complie改成了implementation了，还有一个编译报错

### ISSUE THREAD

**Issue by liqianjiang** [meituan/WMRouter#34]
Caused by: java.lang.NullPointerException
	at com.sankuai.waimai.router.compiler.BaseProcessor.typeMirror(BaseProcessor.java:58)
	at com.sankuai.waimai.router.compiler.BaseProcessor.isSubType(BaseProcessor.java:80)
	at com.sankuai.waimai.router.compiler.BaseProcessor.isSubType(BaseProcessor.java:84)
	at com.sankuai.waimai.router.compiler.BaseProcessor.isConcreteSubType(BaseProcessor.java:103)
	at com.sankuai.waimai.router.compiler.BaseProcessor.isHandler(BaseProcessor.java:118)
	at com.sankuai.waimai.router.compiler.UriAnnotationProcessor.process(UriAnnotationProce。

**Comment by jzj1993** [comment]
没有复现这种问题，暂时没法解决。如果能提供一个可以复现问题的Demo工程最佳~
